/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AbBall: typeof import('./src/components/abBall.vue')['default']
    AbIcon: typeof import('./src/components/abIcon.vue')['default']
    AbNumInput: typeof import('./src/components/abNumInput.vue')['default']
    AbOrderItem: typeof import('./src/components/abOrderItem.vue')['default']
    AbPage: typeof import('./src/components/abPage.vue')['default']
    AbTabbar: typeof import('./src/components/abTabbar.vue')['default']
    AbToast: typeof import('./src/components/abToast.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui')['ActionSheet']
    NutAnimate: typeof import('@nutui/nutui')['Animate']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutBacktop: typeof import('@nutui/nutui')['Backtop']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCalendar: typeof import('@nutui/nutui')['Calendar']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCheckbox: typeof import('@nutui/nutui')['Checkbox']
    NutDialog: typeof import('@nutui/nutui')['Dialog']
    NutEmpty: typeof import('@nutui/nutui')['Empty']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutImage: typeof import('@nutui/nutui')['Image']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutInputNumber: typeof import('@nutui/nutui')['InputNumber']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutOverlay: typeof import('@nutui/nutui')['Overlay']
    NutPicker: typeof import('@nutui/nutui')['Picker']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutPrice: typeof import('@nutui/nutui')['Price']
    NutPullRefresh: typeof import('@nutui/nutui')['PullRefresh']
    NutRadio: typeof import('@nutui/nutui')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui')['RadioGroup']
    NutSearchbar: typeof import('@nutui/nutui')['Searchbar']
    NutSticky: typeof import('@nutui/nutui')['Sticky']
    NutSwipe: typeof import('@nutui/nutui')['Swipe']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTable: typeof import('@nutui/nutui')['Table']
    NutTabPane: typeof import('@nutui/nutui')['TabPane']
    NutTabs: typeof import('@nutui/nutui')['Tabs']
    NutTag: typeof import('@nutui/nutui')['Tag']
    NutUploader: typeof import('@nutui/nutui')['Uploader']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotDemo: typeof import('./src/components/slotDemo.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon.vue')['default']
  }
}
